name: gpgn-318
channels:
- conda-forge
dependencies:
- python=3.10
- discretize=0.9.0
- geoana=0.5.0
- SimPEG=0.20
- pandas
- matplotlib
- jupyterlab
- ipywidgets
- ipympl
- ipyleaflet
- pyvista
- trame
- vtk>=9.2